name: build and release

on: workflow_dispatch

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Set up Go
      uses: actions/setup-go@v3
      with:
        go-version: 1.19
    - name: Build
      run: make release
    - name: Upload artifact
      uses: actions/upload-artifact@v3
      with:
        name: artifact
        path: bin/wspipe

  release:
    runs-on: ubuntu-latest
    needs: build
    steps:
    - name: Download artifact
      uses: actions/download-artifact@v3
      with:
        name: artifact
        path: ./
    - name: Upload to Release
      uses: softprops/action-gh-release@v1
      with:
        draft: true
        files: |
          wspipe
